export { MusicPlayerWidget } from './music-player'
export { ChessWidget } from './chess'
export { SocialMediaWidget } from './social-media'
export { PokemonWidget } from './pokemon-widget'
export { TerminalWidget } from './terminal-widget'
