import type { Metadata } from "next";
import "./globals.css";
import MainProvider from "@/common/provider/main-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <MainProvider>
          {children}
        </MainProvider>
      </body>
    </html >
  );
}
