import type { Metadata } from 'next'
import './globals.css'
import MainProvider from '@/common/provider/main-provider'
import { ThemeProvider } from '@/common/provider/theme-provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <MainProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </MainProvider>
      </body>
    </html>
  )
}
