// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface IExperienceFields {
  /** title */
  title: string;

  /** type */
  type: "Education" | "Work";

  /** ocupation */
  ocupation: string;

  /** description */
  description: string;

  /** date */
  date: string;

  /** link */
  link?: string | undefined;

  /** show_in_cv */
  showInCv: boolean;
}

export interface IExperience extends Entry<IExperienceFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "experience";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IHobbiesFields {
  /** name */
  name: string;

  /** icon */
  icon: "chess" | "music" | "code" | "brush" | "airplane";

  /** description */
  description: string;

  /** show_in_cv */
  showInCv: boolean;
}

export interface IHobbies extends Entry<IHobbiesFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "hobbies";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IMusicWidgetFields {
  /** name */
  name: string;

  /** artist */
  artist: string;

  /** cover */
  cover: string;

  /** audio_url */
  audioUrl: string;
}

export interface IMusicWidget extends Entry<IMusicWidgetFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "musicWidget";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IProfileFields {
  /** avatar */
  avatar: Asset;

  /** full_name */
  fullName: string;

  /** first_name */
  firstName: string;

  /** last_name */
  lastName: string;

  /** short_description */
  shortDescription: string;

  /** email */
  email: string;

  /** phone */
  phone: string;

  /** location */
  location: string;

  /** birthday */
  birthday: string;

  /** biography */
  biography: Document;

  /** languages */
  languages: string;

  /** role_titles */
  roleTitles: string[];

  /** Services */
  services?: IServices[] | undefined;

  /** Experience */
  experience?: IExperience[] | undefined;

  /** Skills */
  skills?: IStackSkills[] | undefined;
}

export interface IProfile extends Entry<IProfileFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "profile";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IProjectsFields {
  /** title */
  title: string;

  /** slug */
  slug: string;

  /** description */
  description: string;

  /** categories */
  categories: ("Back-end" | "Design UI/UX" | "Figma" | "Front-end" | "Web")[];
}

export interface IProjects extends Entry<IProjectsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "projects";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IServicesFields {
  /** title */
  title: string;

  /** description */
  description: string;

  /** show_in_cv */
  showInCv: boolean;
}

export interface IServices extends Entry<IServicesFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "services";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IStackSkillsFields {
  /** name */
  name: string;

  /** types */
  types: (
    | "Backend Development"
    | "CMS"
    | "Database"
    | "E-Commerce"
    | "Frontend Development"
    | "Mobile Development"
    | "ORM"
    | "Programming Languages"
    | "Tools"
  )[];

  /** icon */
  icon: string;

  /** description */
  description: string;

  /** percentage */
  percentage: number;

  /** show_in_cv */
  showInCv: boolean;

  /** component */
  component: "progress bar" | "circular bar" | "badge";
}

export interface IStackSkills extends Entry<IStackSkillsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "stackSkills";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE =
  | "experience"
  | "hobbies"
  | "musicWidget"
  | "profile"
  | "projects"
  | "services"
  | "stackSkills";

export type IEntry =
  | IExperience
  | IHobbies
  | IMusicWidget
  | IProfile
  | IProjects
  | IServices
  | IStackSkills;

export type LOCALE_CODE = "en-US" | "es-MX";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
